/*
 Navicat Premium Dump SQL

 Source Server         : MySQL_8.4.5
 Source Server Type    : MySQL
 Source Server Version : 80405 (8.4.5)
 Source Host           : localhost:3307
 Source Schema         : promptflow

 Target Server Type    : MySQL
 Target Server Version : 80405 (8.4.5)
 File Encoding         : 65001

 Date: 21/04/2026 23:49:26
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for template
-- ----------------------------
DROP TABLE IF EXISTS `template`;
CREATE TABLE `template`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `template_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模板名称',
  `template_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模板类型：CONTENT_GENERATION/PROMPT_GENERATION',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '模板简介',
  `scene_description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '使用场景说明',
  `output_description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '输出说明',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '模板图标',
  `form_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '表单结构JSON',
  `prompt_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '模板配置JSON',
  `sort_num` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_template_code`(`template_code` ASC) USING BTREE,
  INDEX `idx_template_status`(`status` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '模板表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of template
-- ----------------------------
INSERT INTO `template` VALUES (1, 'ai_cover_prompt', 'AI翻唱提示词生成', 'PROMPT_GENERATION', '根据歌曲、风格、歌手等生成AI翻唱提示词', '适用于AI翻唱、风格改编', '输出结构化Prompt，可直接用于Suno', 'fas fa-music', '[\r\n  {\r\n    \"fieldKey\": \"songName\",\r\n    \"label\": \"原歌曲名称\",\r\n    \"componentType\": \"input\",\r\n    \"required\": true,\r\n    \"placeholder\": \"例如：夜曲 - 周杰伦\"\r\n  },\r\n  {\r\n    \"fieldKey\": \"style\",\r\n    \"label\": \"改编风格\",\r\n    \"componentType\": \"select\",\r\n    \"required\": true,\r\n    \"placeholder\": \"请选择一种音乐风格（如R&B、Acoustic）\",\r\n    \"options\": [\r\n      { \"label\": \"R&B\", \"value\": \"R&B\" },\r\n      { \"label\": \"Funk\", \"value\": \"Funk\" },\r\n      { \"label\": \"J-Pop\", \"value\": \"J-Pop\" },\r\n      { \"label\": \"合成器流行\", \"value\": \"Synthpop\" },\r\n      { \"label\": \"原声\", \"value\": \"Acoustic\" },\r\n      { \"label\": \"灵魂流行\", \"value\": \"Pop Soul\" }\r\n    ]\r\n  },\r\n  {\r\n    \"fieldKey\": \"artist\",\r\n    \"label\": \"参考歌手 / 声线\",\r\n    \"componentType\": \"input\",\r\n    \"required\": false,\r\n    \"placeholder\": \"例如：类似Justin Bieber的温柔男声\"\r\n  },\r\n  {\r\n    \"fieldKey\": \"mood\",\r\n    \"label\": \"情绪氛围\",\r\n    \"componentType\": \"tag\",\r\n    \"required\": false,\r\n    \"options\": [\r\n      { \"label\": \"慵懒\", \"value\": \"lazy\" },\r\n      { \"label\": \"浪漫\", \"value\": \"romantic\" },\r\n      { \"label\": \"都市感\", \"value\": \"urban\" },\r\n      { \"label\": \"忧郁\", \"value\": \"melancholic\" },\r\n      { \"label\": \"明亮\", \"value\": \"bright\" },\r\n      { \"label\": \"活泼\", \"value\": \"playful\" },\r\n      { \"label\": \"史诗感\", \"value\": \"epic\" }\r\n    ]\r\n  },\r\n  {\r\n    \"fieldKey\": \"tempo\",\r\n    \"label\": \"节奏感\",\r\n    \"componentType\": \"select\",\r\n    \"required\": false,\r\n    \"placeholder\": \"请选择节奏感\",\r\n    \"options\": [\r\n      { \"label\": \"慢速\", \"value\": \"slow tempo\" },\r\n      { \"label\": \"中速\", \"value\": \"medium tempo\" },\r\n      { \"label\": \"快速\", \"value\": \"fast tempo\" }\r\n    ]\r\n  },\r\n  {\r\n    \"fieldKey\": \"language\",\r\n    \"label\": \"输出语言\",\r\n    \"componentType\": \"radio\",\r\n    \"required\": true,\r\n    \"defaultValue\": \"English\",\r\n    \"options\": [\r\n      { \"label\": \"中文\", \"value\": \"Chinese\" },\r\n      { \"label\": \"英文\", \"value\": \"English\" }\r\n    ]\r\n  },\r\n  {\r\n    \"fieldKey\": \"extraRemark\",\r\n    \"label\": \"附加说明\",\r\n    \"componentType\": \"textarea\",\r\n    \"required\": false,\r\n    \"placeholder\": \"例如：前奏加入一段萨克斯，整体偏深夜都市氛围\"\r\n  }\r\n]', '{\n  \"promptFile\": \"prompts/ai_cover_prompt.txt\",\n  \"maxLength\": 1000\n}', 1, 1, '2026-04-13 12:17:30', '2026-04-21 13:30:27');
INSERT INTO `template` VALUES (2, 'ai_short_video_script', '短视频脚本生成', 'CONTENT_GENERATION', '根据主题、受众和风格生成短视频脚本内容', '适用于抖音、小红书、快手等平台内容创作', '输出分镜化或分段式短视频脚本文案', 'fas fa-film', '[\r\n    {\r\n      \"fieldKey\": \"topic\",\r\n      \"label\": \"视频主题\",\r\n      \"componentType\": \"input\",\r\n      \"required\": true\r\n    },\r\n    {\r\n      \"fieldKey\": \"targetAudience\",\r\n      \"label\": \"目标用户\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"style\",\r\n      \"label\": \"脚本风格\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"duration\",\r\n      \"label\": \"视频时长\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"extraRemark\",\r\n      \"label\": \"补充说明\",\r\n      \"componentType\": \"textarea\"\r\n    }\r\n  ]', '{\r\n    \"promptFile\": \"ai_short_video_script.txt\",\r\n    \"maxLength\": 1500\r\n  }', 4, 0, '2026-04-20 21:55:07', '2026-04-21 13:29:13');
INSERT INTO `template` VALUES (3, 'ai_social_post', '小红书爆款文案', 'CONTENT_GENERATION', '根据主题和语气生成适合社交平台发布的文案', '生成吸引眼球的小红书风格文案', '输出可直接发布或二次修改的社交媒体文案', 'fas fa-book-open', '[\r\n    {\r\n      \"fieldKey\": \"topic\",\r\n      \"label\": \"文案主题\",\r\n      \"componentType\": \"input\",\r\n      \"required\": true\r\n    },\r\n    {\r\n      \"fieldKey\": \"platform\",\r\n      \"label\": \"发布平台\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"tone\",\r\n      \"label\": \"语气风格\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"keywords\",\r\n      \"label\": \"关键词\",\r\n      \"componentType\": \"textarea\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"extraRemark\",\r\n      \"label\": \"补充要求\",\r\n      \"componentType\": \"textarea\"\r\n    }\r\n  ]', '{\r\n    \"promptFile\": \"ai_social_post.txt\",\r\n    \"maxLength\": 1200\r\n  }', 5, 0, '2026-04-20 21:55:07', '2026-04-21 13:29:44');
INSERT INTO `template` VALUES (4, 'ai_title_optimizer', '社交媒体文案', 'CONTENT_GENERATION', '为各大社交平台定制文案', '适用于短视频、文章、笔记、海报标题等场景', '输出多个标题候选，便于筛选使用', 'fas fa-hashtag', '[\r\n    {\r\n      \"fieldKey\": \"topic\",\r\n      \"label\": \"内容主题\",\r\n      \"componentType\": \"input\",\r\n      \"required\": true\r\n    },\r\n   {\r\n  \"fieldKey\": \"platform\",\r\n  \"label\": \"平台\",\r\n  \"componentType\": \"input\"\r\n},\r\n    {\r\n      \"fieldKey\": \"style\",\r\n      \"label\": \"标题风格\",\r\n      \"componentType\": \"input\"\r\n    },\r\n    {\r\n      \"fieldKey\": \"keywords\",\r\n      \"label\": \"关键词\",\r\n      \"componentType\": \"textarea\"\r\n    }\r\n  ]', '{\r\n    \"promptFile\": \"ai_title_optimizer.txt\",\r\n    \"maxLength\": 800\r\n  }', 6, 0, '2026-04-20 21:55:07', '2026-04-21 13:34:47');

-- ----------------------------
-- Table structure for workflow_run
-- ----------------------------
DROP TABLE IF EXISTS `workflow_run`;
CREATE TABLE `workflow_run`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `template_id` bigint NOT NULL COMMENT '模板ID',
  `template_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模板编码',
  `run_status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '运行状态：PENDING/RUNNING/SUCCESS/FAILED',
  `input_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '输入数据JSON',
  `result_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '最终结果JSON',
  `extra_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '附加信息JSON',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '错误信息',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_workflow_run_template_id`(`template_id` ASC) USING BTREE,
  INDEX `idx_workflow_run_template_code`(`template_code` ASC) USING BTREE,
  INDEX `idx_workflow_run_status`(`run_status` ASC) USING BTREE,
  INDEX `idx_workflow_run_created_at`(`created_at` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 61 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '流程运行记录表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of workflow_run
-- ----------------------------
INSERT INTO `workflow_run` VALUES (3, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', 'AI生成结果：\n【身份设定】\n你是一个专业的音乐制作人和AI音乐生成专家（例如Suno/Udio的提示词编写专家）。\n\n【原曲信息】\n歌曲名称：美人鱼\n\n【改编要求】\n1. 核心风格 (Style)：Acoustic R&B with Pop Soul\n2. 情绪氛围 (Mood)：慵懒\n3. 节奏感 (Tempo)：中速\n4. 演唱声线 (Vocal)：Justin Bieber，男声\n5. 输出语言 (Language)：英文\n\n【附加说明】\n前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\n\n【输出要求】\n请根据上述要求，直接输出一段可用于AI音乐大模型（如Suno）的高质量、结构化的Prompt（包含 [Intro], [Verse], [Chorus], [Outro] 等标签），不要输出任何解释性废话。\n\n（此为模拟结果，实际由AI模型生成）', '{\"tokenUsage\":100,\"model\":\"mock-ai-model\"}', NULL, '2026-04-13 17:04:53', '2026-04-13 17:04:53');
INSERT INTO `workflow_run` VALUES (5, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '[Intro]\nAcoustic R&B with Pop Soul, lazy and smooth mood, medium tempo, urban night vibe, soft saxophone melody in the background, gentle guitar plucking, warm and intimate atmosphere, male vocal similar to Justin Bieber\'s tone, breathy and relaxed delivery, subtle reverb, nighttime city soundscape\n\n[Verse]\nSoft acoustic guitar rhythm, laid-back R&B groove, smooth bassline, light finger snaps, intimate vocal delivery, lyrics about a mysterious mermaid under city lights, nostalgic and dreamy, gentle keyboard pads, subtle vinyl crackle, vocal harmonies in the background, emotional and personal storytelling\n\n[Chorus]\nSoulful pop melody, uplifting yet relaxed, fuller instrumentation with added strings, layered vocal harmonies, catchy hook about longing and fantasy, dynamic drum pattern with soft cymbals, warm synth pads, emotional build-up, romantic and yearning atmosphere, smooth transitions\n\n[Bridge]\nMinimal arrangement, focus on vocal vulnerability, atmospheric saxophone solo, echoing effects, slow tempo drop, introspective lyrics, ambient background textures, emotional climax, gradual build-up with added percussion\n\n[Outro]\nFading acoustic elements, lingering saxophone notes, gentle vocal ad-libs, reverb-drenched atmosphere, slow fade-out with distant city sounds, nighttime ambiance, melancholic yet peaceful ending, sustained keyboard chords', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-13 19:29:53', '2026-04-13 19:30:05');
INSERT INTO `workflow_run` VALUES (6, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', 'Original Style Analysis:\nLikely a sentimental Chinese pop ballad.\n\nStyle:\nAcoustic R&B infused with Pop Soul.\n\nTempo:\nMedium tempo, around 80-85 BPM.\n\nKey:\nF major.\n\nArrangement:\nAcoustic guitar foundation, warm bass, subtle electric piano, soft pads, and a gentle saxophone intro for atmosphere.\n\nGroove:\nLaid-back, steady R&B pocket with a relaxed swing.\n\nVocal:\nSmooth, breathy, and intimate male vocal with light falsetto ad-libs; conversational phrasing.\n\nMood:\nLazy, introspective, and smooth; perfect for a late-night urban drive.', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-13 20:27:02', '2026-04-13 20:27:09');
INSERT INTO `workflow_run` VALUES (7, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', 'Original Style Analysis:\nLikely a sentimental Chinese pop ballad.\n\nStyle:\nAcoustic R&B infused with Pop Soul.\n\nTempo:\nMid-tempo, around 85 BPM.\n\nKey:\nF major.\n\nArrangement:\nWarm acoustic guitar chords, subtle electric piano pads, soft bassline, and light atmospheric saxophone in the intro.\n\nGroove:\nSmooth, laid-back R&B pocket with a gentle swing.\n\nVocal:\nBreathy, relaxed male tenor with soulful melisma and effortless, conversational phrasing.\n\nMood:\nLazy, intimate, and reflective; perfect for a late-night urban drive.', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 10:54:35', '2026-04-14 10:54:41');
INSERT INTO `workflow_run` VALUES (8, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"playful\"],\"tempo\":\"medium tempo\",\"language\":\"English\",\"extraRemark\":\"\"}', 'Original Style Analysis:\nA melancholic Chinese pop ballad with classical influences.\n\nStyle:\nContemporary R&B with a playful twist.\n\nTempo:\nMedium tempo, 92 BPM.\n\nKey:\nF minor.\n\nArrangement:\nWarm, filtered synth pads, a crisp finger-snap and clap beat, smooth electric bass line, and sparse, jazzy electric piano chords.\n\nGroove:\nA laid-back, syncopated 4/4 groove with a subtle swing.\n\nVocal:\nSmooth, breathy tenor with a playful, conversational delivery; light falsetto runs and melodic ad-libs.\n\nMood:\nPlayful and flirtatious, perfect for a late-night, intimate setting.', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 11:52:27', '2026-04-14 11:52:35');
INSERT INTO `workflow_run` VALUES (9, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"Funk\",\"artist\":\"类似陶喆的声线\",\"mood\":[\"romantic\"],\"tempo\":\"medium tempo\",\"language\":\"English\",\"extraRemark\":\"吉他伴奏\"}', 'Original Style Analysis:\nA melancholic Chinese pop ballad.\n\nStyle:\nFunk-infused romantic pop.\n\nTempo:\nMedium tempo, 98 BPM.\n\nKey:\nF major.\n\nArrangement:\nFunky rhythm guitar, tight bassline, crisp drums, warm synth pads. Lead guitar accents.\n\nGroove:\nSyncopated, bouncy, and danceable.\n\nVocal:\nSmooth, soulful tenor with expressive R&B phrasing and slight rasp.\n\nMood:\nRomantic, smooth, and intimate; perfect for a late-night drive.', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 11:58:16', '2026-04-14 11:58:20');
INSERT INTO `workflow_run` VALUES (10, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', 'Original Style Analysis:\nA classic Chinese ballad with sentimental melody and traditional arrangement.\n\nStyle:\nAcoustic R&B infused with Pop Soul.\n\nTempo:\nMid-tempo, 85 BPM.\n\nKey:\nF Major.\n\nArrangement:\nAcoustic guitar foundation, subtle electric piano chords, warm bassline, and light atmospheric saxophone in the intro and transitions.\n\nGroove:\nLaid-back, steady R&B pocket with a gentle swing.\n\nVocal:\nSmooth, breathy tenor with relaxed phrasing and light falsetto runs, inspired by Justin Bieber\'s contemporary R&B delivery.\n\nMood:\nLazy, intimate, and nocturnal; perfect for late-night urban vibes.', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 12:08:28', '2026-04-14 12:08:34');
INSERT INTO `workflow_run` VALUES (11, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"Mood\":\"Lazy, intimate, and contemplative; perfect for a late-night urban drive.\",\"Tempo\":\"Medium tempo, around 80 BPM.\",\"Groove\":\"Laid-back, steady R&B groove with a soft shuffle.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy, and relaxed male vocal with gentle falsetto runs. Intimate, conversational phrasing.\",\"Original Style Analysis\":\"A classic Chinese pop ballad with sentimental melodies.\",\"Key\":\"F Major.\",\"Arrangement\":\"Warm acoustic guitar chords, subtle electric piano, soft bass, and a gentle saxophone pad in the intro. Clean, spacious production with urban nightlife atmosphere.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 12:15:42', '2026-04-14 12:15:48');
INSERT INTO `workflow_run` VALUES (12, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"陶喆\",\"mood\":[\"romantic\"],\"tempo\":\"medium tempo\",\"language\":\"Chinese\",\"extraRemark\":\"\"}', '{\"Mood\":\"浪漫、私密、适合夜晚聆听的都市情感氛围。\",\"Tempo\":\"中速，约85 BPM\",\"Groove\":\"流畅的切分节奏与反拍律动\",\"Style\":\"R&B融合流行与灵魂乐\",\"Vocal\":\"陶喆式的丝滑、富有表现力的假声与转音，情感细腻的都市化人声演绎。\",\"Original Style Analysis\":\"原曲为周杰伦的古典钢琴流行情歌。\",\"Key\":\"降E大调\",\"Arrangement\":\"简约的钢琴与电吉他旋律线，搭配扎实的合成贝斯和清脆的电子鼓组，点缀氛围感合成器铺底。\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 12:27:11', '2026-04-14 12:27:16');
INSERT INTO `workflow_run` VALUES (13, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night, introspective, and melancholic vibe for solitary reflection.\",\"Tempo\":\"70 BPM.\",\"Groove\":\"A slow, steady, and hypnotic half-time beat.\",\"Style\":\"Contemporary R&B with atmospheric pop sensibilities.\",\"Vocal\":\"Smooth, breathy, and emotive male vocal with gentle falsetto runs and intimate phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with piano and strings.\",\"Key\":\"F minor.\",\"Arrangement\":\"Sparse, deep 808 bass, crisp finger snaps, atmospheric synth pads, and subtle electric piano chords.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 12:30:23', '2026-04-14 12:30:29');
INSERT INTO `workflow_run` VALUES (14, 1, 'ai_cover_prompt', 'RUNNING', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', NULL, NULL, NULL, '2026-04-14 15:20:25', '2026-04-14 15:20:25');
INSERT INTO `workflow_run` VALUES (15, 1, 'ai_cover_prompt', 'RUNNING', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', NULL, NULL, NULL, '2026-04-14 15:20:54', '2026-04-14 15:20:54');
INSERT INTO `workflow_run` VALUES (16, 1, 'ai_cover_prompt', 'RUNNING', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', NULL, NULL, NULL, '2026-04-14 15:21:25', '2026-04-14 15:21:25');
INSERT INTO `workflow_run` VALUES (17, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"Mood\":\"Lazy, intimate, and urban nighttime vibe.\",\"Tempo\":\"Mid-tempo, around 85 BPM.\",\"Groove\":\"Laid-back, steady R&B pocket with a soft shuffle.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy, and relaxed tenor with gentle falsetto runs and soulful ad-libs.\",\"Original Style Analysis\":\"Likely a sentimental Chinese pop ballad.\",\"Key\":\"G Major.\",\"Arrangement\":\"Acoustic guitar foundation with warm bass, subtle electric piano, and light atmospheric saxophone in the intro.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 15:24:34', '2026-04-14 15:24:41');
INSERT INTO `workflow_run` VALUES (18, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"J-Pop\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Nostalgic and bittersweet, suitable for a reflective night drive or late-night listening.\",\"Tempo\":\"75 BPM\",\"Groove\":\"Steady, driving four-on-the-floor with syncopated hi-hats.\",\"Style\":\"J-Pop with a touch of city pop and modern synth-pop.\",\"Vocal\":\"Bright, clear, and youthful female vocal. Airy, emotive phrasing with gentle vibrato and precise enunciation.\",\"Original Style Analysis\":\"Original song is a melancholic Chinese ballad with classical guitar motifs.\",\"Key\":\"E Minor\",\"Arrangement\":\"Clean electric guitar arpeggios, warm synth pads, crisp electronic drums, subtle bassline. Sparkling synth leads in choruses.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 15:25:05', '2026-04-14 15:25:11');
INSERT INTO `workflow_run` VALUES (19, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night introspective and bittersweet, suitable for intimate listening.\",\"Tempo\":\"72 BPM.\",\"Groove\":\"Laid-back, syncopated 6/8 swing with a subtle trap-inspired hi-hat pattern.\",\"Style\":\"Contemporary R&B fusion with soulful pop undertones.\",\"Vocal\":\"Smooth, breathy, and intimate male tenor with gentle falsetto ad-libs and conversational phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese ballad with piano-driven arrangement.\",\"Key\":\"C minor.\",\"Arrangement\":\"Warm, deep synth bass pads, crisp finger-snap percussion, atmospheric synth swells, and sparse electric piano chords.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 15:33:19', '2026-04-14 15:33:26');
INSERT INTO `workflow_run` VALUES (20, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"枫\",\"style\":\"Funk\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Confident, danceable groove with a cool, late-night vibe.\",\"Tempo\":\"110 BPM, upbeat and steady.\",\"Groove\":\"Locked-in, syncopated sixteenth-note funk rhythm.\",\"Style\":\"Modern Funk with a soulful pop crossover.\",\"Vocal\":\"Smooth, soulful male tenor with rhythmic, percussive phrasing and occasional ad-libs.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with piano and strings.\",\"Key\":\"F minor, soulful and driving.\",\"Arrangement\":\"Tight rhythm section with wah-wah guitar, punchy brass stabs, synth bass, and crisp drums. Clean, funky production.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-14 15:35:43', '2026-04-14 15:35:50');
INSERT INTO `workflow_run` VALUES (21, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"lazy\",\"romantic\",\"urban\",\"melancholic\",\"bright\",\"playful\"],\"tempo\":\"129\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Urban, melancholic, and romantic; late-night city drive.\",\"Tempo\":\"129 BPM.\",\"Groove\":\"A laid-back, syncopated 4/4 beat with a subtle swing.\",\"Style\":\"Contemporary R&B with smooth pop sensibilities.\",\"Vocal\":\"Smooth, breathy male tenor with relaxed, melismatic phrasing and soft falsetto ad-libs.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano elements.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep synth pads, crisp finger-snap percussion, a prominent melodic bassline, and atmospheric synth textures.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 11:45:43', '2026-04-15 11:45:50');
INSERT INTO `workflow_run` VALUES (22, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Intimate, late-night reflective and bittersweet.\",\"Tempo\":\"70 BPM.\",\"Groove\":\"A smooth, laid-back, and syncopated rhythm.\",\"Style\":\"Contemporary R&B with soulful pop fusion.\",\"Vocal\":\"Soulful, breathy male tenor with gentle falsetto ad-libs and emotive, legato phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano elements.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep synth pads, a prominent electric bass line, crisp finger-snap percussion, and atmospheric vocal layers.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 11:46:21', '2026-04-15 11:46:26');
INSERT INTO `workflow_run` VALUES (23, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Introspective and bittersweet; late-night reflection.\",\"Tempo\":\"75 BPM.\",\"Groove\":\"A laid-back, syncopated 6/8 swing.\",\"Style\":\"Contemporary R&B with atmospheric pop sensibilities.\",\"Vocal\":\"Smooth, breathy tenor with intimate, conversational phrasing. Gentle falsetto runs and subtle ad-libs.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano motifs.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep 808 bass, crisp finger-snaps, airy synth pads, and sparse, processed piano chords. Subtle vocal layers and reverb tails.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 12:10:53', '2026-04-15 12:10:59');
INSERT INTO `workflow_run` VALUES (24, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night introspective and melancholic, perfect for solitary reflection.\",\"Tempo\":\"70 BPM.\",\"Groove\":\"A laid-back, syncopated 6/8 swing.\",\"Style\":\"Contemporary R&B with atmospheric pop undertones.\",\"Vocal\":\"Smooth, breathy, and soulful male tenor with gentle falsetto ad-libs. Intimate, conversational phrasing with slight vocal fry.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano elements.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep synth pads, a prominent electric bass line, crisp finger-snaps, and subtle trap hi-hats. Atmospheric synth swells and reverb-drenched piano chords.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 12:11:41', '2026-04-15 12:11:48');
INSERT INTO `workflow_run` VALUES (25, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night introspective and melancholic, perfect for solitary reflection.\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, swung 6/8 rhythm with a subtle bounce.\",\"Style\":\"Contemporary R&B with smooth soul and atmospheric pop influences.\",\"Vocal\":\"Smooth, breathy, and soulful male tenor with gentle falsetto flourishes and intimate, conversational phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano motifs.\",\"Key\":\"F minor\",\"Arrangement\":\"Warm, deep 808 bass, crisp finger-snaps, atmospheric synth pads, and sparse, clean electric guitar licks. Subtle vinyl crackle texture.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 12:14:07', '2026-04-15 12:14:13');
INSERT INTO `workflow_run` VALUES (26, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Introspective, late-night melancholy; suitable for reflective listening.\",\"Tempo\":\"85 BPM.\",\"Groove\":\"A laid-back, syncopated drum pattern with a steady, pulsing kick.\",\"Style\":\"Contemporary R&B with atmospheric pop undertones.\",\"Vocal\":\"Smooth, breathy, and emotive male vocal with gentle falsetto runs and intimate, conversational phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano elements.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep synth pads, a prominent electric piano melody, and a tight, side-chained kick and snare drum pattern. Subtle sub-bass and atmospheric soundscapes.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 12:17:46', '2026-04-15 12:17:52');
INSERT INTO `workflow_run` VALUES (27, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"Pop Soul\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Reflective and bittersweet, suitable for late-night listening.\",\"Tempo\":\"72 BPM\",\"Groove\":\"A laid-back, steady 4/4 with a subtle swing.\",\"Style\":\"Pop Soul with R&B influences\",\"Vocal\":\"Smooth, emotive tenor with soulful melisma and gentle falsetto runs. Intimate, breathy phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with piano and strings.\",\"Key\":\"F Major\",\"Arrangement\":\"Warm electric piano, tight bassline, crisp drum kit, subtle string pads, and soulful guitar licks.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-15 17:10:09', '2026-04-15 17:10:17');
INSERT INTO `workflow_run` VALUES (28, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Introspective, late-night melancholy; a moody, atmospheric vibe for reflection.\",\"Tempo\":\"72 BPM.\",\"Groove\":\"A laid-back, syncopated 6/8 swing feel.\",\"Style\":\"Contemporary R&B with smooth soul and modern pop influences.\",\"Vocal\":\"Smooth, breathy, and emotive male tenor with gentle falsetto flourishes and intimate, conversational phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano elements.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep synth pads, a prominent electric bass line, crisp finger-snap percussion, and atmospheric synth textures. Subtle, processed electric guitar licks.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 21:56:46', '2026-04-17 21:56:53');
INSERT INTO `workflow_run` VALUES (29, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"Mood\":\"Lazy, intimate, and wistful; perfect for a late-night urban drive.\",\"Tempo\":\"Medium tempo, around 85 BPM.\",\"Groove\":\"Laid-back, steady R&B groove with a soft shuffle.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy, and relaxed male vocal with gentle falsetto runs and soulful, conversational phrasing.\",\"Original Style Analysis\":\"Likely a sentimental Chinese pop ballad.\",\"Key\":\"F major.\",\"Arrangement\":\"Acoustic guitar foundation, warm bass, subtle electric piano, and light atmospheric saxophone in the intro. Clean, spacious production with urban night ambiance.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:05:46', '2026-04-17 22:05:52');
INSERT INTO `workflow_run` VALUES (30, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night, introspective, and bittersweet reflection.\",\"Tempo\":\"70 BPM.\",\"Groove\":\"A laid-back, swung, and syncopated rhythm.\",\"Style\":\"Contemporary R&B with soulful pop fusion.\",\"Vocal\":\"Smooth, breathy, and emotive male tenor with subtle melisma and intimate, conversational phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano motifs.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep 808 bass, crisp finger-snaps, atmospheric synth pads, and sparse, clean electric guitar licks.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:25:24', '2026-04-17 22:25:29');
INSERT INTO `workflow_run` VALUES (31, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"Mood\":\"Late-night introspective and melancholic, perfect for solitary reflection.\",\"Tempo\":\"70 BPM.\",\"Groove\":\"A slow, swung, and syncopated beat with a laid-back pocket.\",\"Style\":\"Contemporary R&B with atmospheric pop fusion.\",\"Vocal\":\"Smooth, breathy, and emotive male tenor. Uses subtle melisma and intimate, close-mic phrasing.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano motifs.\",\"Key\":\"F minor.\",\"Arrangement\":\"Warm, deep 808 sub-bass, crisp trap hi-hats, and atmospheric synth pads. A filtered electric piano carries the main melody.\"}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:26:45', '2026-04-17 22:26:51');
INSERT INTO `workflow_run` VALUES (32, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":null,\"coverText\":null,\"tags\":null,\"suggestion\":null,\"prompt\":{\"Mood\":\"Lazy, intimate, and contemplative; perfect for late-night city drives.\",\"Tempo\":\"Mid-tempo, around 85 BPM.\",\"Groove\":\"Laid-back, steady R&B pocket with a soft swing.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy tenor with relaxed, conversational phrasing and light falsetto runs.\",\"Original Style Analysis\":\"Likely a sentimental Chinese pop ballad.\",\"Key\":\"F Major.\",\"Arrangement\":\"Acoustic guitar and warm bass foundation, with subtle atmospheric saxophone in the intro and sparse, shimmering electric piano chords. Clean, tight drum programming.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:34:33', '2026-04-17 22:34:39');
INSERT INTO `workflow_run` VALUES (33, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":null,\"coverText\":null,\"tags\":null,\"suggestion\":null,\"prompt\":{\"Mood\":\"Introspective, late-night solitude with a touch of wistful romance.\",\"Tempo\":\"70 BPM\",\"Groove\":\"A laid-back, syncopated 6/8 swing feel.\",\"Style\":\"Contemporary R&B infused with atmospheric pop.\",\"Vocal\":\"Smooth, breathy, and emotive male tenor. Uses gentle falsetto runs and intimate, conversational phrasing with subtle vocal layering.\",\"Original Style Analysis\":\"A melancholic Chinese pop ballad with classical piano motifs.\",\"Key\":\"C minor\",\"Arrangement\":\"Warm, deep synth pads, crisp finger-snap percussion, a smooth sub-bass line, and subtle atmospheric textures. Clean electric piano chords for harmonic foundation.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:35:10', '2026-04-17 22:35:16');
INSERT INTO `workflow_run` VALUES (34, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":\"把这首歌改成Acoustic R&B with Pop Soul翻唱，氛围感直接拉满\",\"coverText\":\"美人鱼｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#美人鱼\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, intimate, and wistful; perfect for late-night city drives.\",\"Tempo\":\"Mid-tempo, 80 BPM.\",\"Groove\":\"Laid-back, steady 6/8 shuffle with soft finger snaps.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy tenor with relaxed phrasing and light falsetto runs. Casual, intimate delivery.\",\"Original Style Analysis\":\"Likely a sentimental Chinese pop ballad.\",\"Key\":\"F Major.\",\"Arrangement\":\"Acoustic guitar foundation, warm bass, subtle electric piano chords, gentle saxophone accents in intro and pads. Clean, spacious urban night mix.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-17 22:57:50', '2026-04-17 22:57:57');
INSERT INTO `workflow_run` VALUES (35, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":\"Late night acoustic cover of 《美人鱼》\",\"coverText\":\"如果《美人鱼》变成翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#美人鱼\",\"#Soul音乐\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, intimate, and contemplative; perfect for a late-night urban vibe.\",\"Tempo\":\"Medium tempo, around 92 BPM.\",\"Groove\":\"Laid-back, steady R&B groove with a gentle swing.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy male vocal with relaxed phrasing and light falsetto ad-libs, inspired by Justin Bieber\'s tone.\",\"Original Style Analysis\":\"Likely a sentimental Chinese pop ballad.\",\"Key\":\"F Major.\",\"Arrangement\":\"Acoustic guitar foundation, subtle ambient saxophone intro, warm bass, soft electric piano pads, and crisp finger snaps.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:33:06', '2026-04-18 00:33:15');
INSERT INTO `workflow_run` VALUES (36, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"美人鱼\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":\"慵懒翻唱《美人鱼》的夜晚\",\"coverText\":\"美人鱼｜流行翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#美人鱼\",\"#流行翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, intimate, and contemplative; perfect for a late-night urban vibe.\",\"Tempo\":\"Medium, 85 BPM.\",\"Groove\":\"Laid-back, steady 4/4 with a gentle swing.\",\"Style\":\"Acoustic R&B with Pop Soul.\",\"Vocal\":\"Smooth, breathy tenor with Justin Bieber-inspired phrasing. Relaxed delivery, light falsetto ad-libs.\",\"Original Style Analysis\":\"Likely a sentimental Chinese ballad.\",\"Key\":\"F Major.\",\"Arrangement\":\"Acoustic guitar foundation, subtle atmospheric saxophone intro, warm bass, soft electric piano pads, crisp finger snaps.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:43:20', '2026-04-18 00:43:27');
INSERT INTO `workflow_run` VALUES (37, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"perfect\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":\"慵懒夜晚的《perfect》心动翻唱\",\"coverText\":\"perfect｜流行翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#perfect\",\"#流行翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, intimate, and romantic; perfect for a late-night city drive.\",\"Tempo\":\"Medium tempo, 85 BPM.\",\"Groove\":\"Laid-back, steady 4/4 with a gentle swing.\",\"Style\":\"Acoustic R&B infused with Pop Soul.\",\"Vocal\":\"Smooth, breathy tenor with Justin Bieber-inspired melodic runs and intimate, relaxed phrasing.\",\"Original Style Analysis\":\"Original likely a romantic pop ballad.\",\"Key\":\"F Major.\",\"Arrangement\":\"Acoustic guitar foundation, subtle ambient saxophone intro, warm bass, soft electric piano pads, and crisp finger snaps. Urban night vibe.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:43:47', '2026-04-18 00:43:53');
INSERT INTO `workflow_run` VALUES (38, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"perfect\",\"style\":\"R&B\",\"artist\":\"伍佰\",\"mood\":[\"romantic\",\"lazy\"],\"tempo\":\"80\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"A lazy romantic cover of 《perfect》\",\"coverText\":\"perfect｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#perfect\",\"#R&B翻唱\",\"#情歌\",\"#慢节奏\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏放慢，突出情绪，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Intimate, lazy, and warmly romantic; perfect for a cozy evening in.\",\"Tempo\":\"80 BPM\",\"Groove\":\"A relaxed, laid-back 6/8 sway with a gentle backbeat.\",\"Style\":\"R&B ballad with a touch of singer-songwriter intimacy.\",\"Vocal\":\"Smooth, slightly raspy baritone with a conversational, intimate delivery. Breathier tone for a romantic feel, using subtle melisma.\",\"Original Style Analysis\":\"Original is a pop ballad with piano and strings.\",\"Key\":\"G Major\",\"Arrangement\":\"Warm, clean fingerstyle guitar accompaniment as the core, subtle bass, soft electric piano pads, and sparse, crisp drum programming.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:46:49', '2026-04-18 00:46:56');
INSERT INTO `workflow_run` VALUES (39, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"perfect\",\"style\":\"Acoustic R&B with Pop Soul\",\"artist\":\"Justin Bieber\",\"mood\":\"慵懒\",\"tempo\":\"中速\",\"language\":\"英文\",\"extraRemark\":\"前奏加入轻微的萨克斯氛围，整体偏都市夜晚感觉\"}', '{\"title\":\"慵懒翻唱《perfect》的都市夜晚\",\"coverText\":\"perfect｜翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#perfect\",\"#流行翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, intimate, and contemplative; perfect for a late-night city drive.\",\"Tempo\":\"Mid-tempo, 92 BPM\",\"Groove\":\"Laid-back, steady 4/4 with a gentle swing.\",\"Style\":\"Acoustic R&B with Pop Soul\",\"Vocal\":\"Smooth, breathy, and relaxed tenor phrasing with subtle R&B melismas, inspired by Justin Bieber\'s tone.\",\"Original Style Analysis\":\"Original likely a romantic pop ballad.\",\"Key\":\"G Major\",\"Arrangement\":\"Acoustic guitar foundation, subtle ambient saxophone intro, warm bass, soft electric piano pads, crisp finger snaps, and sparse synth textures for urban night vibe.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:48:10', '2026-04-18 00:48:17');
INSERT INTO `workflow_run` VALUES (40, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"perfect\",\"style\":\"Funk\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"《Perfect》Funk Remix, Feel the Groove\",\"coverText\":\"perfect这样唱，太动听了\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#perfect\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合多种生活化场景。\",\"prompt\":{\"Mood\":\"Uplifting, confident, perfect for a stylish dance video.\",\"Tempo\":\"112 BPM\",\"Groove\":\"Syncopated, bouncy, and danceable.\",\"Style\":\"Modern Funk, Pop Fusion\",\"Vocal\":\"Smooth, soulful male tenor with rhythmic, conversational phrasing and light falsetto ad-libs.\",\"Original Style Analysis\":\"Original is a romantic pop ballad.\",\"Key\":\"F Major\",\"Arrangement\":\"Tight horn section stabs, wah-wah guitar, prominent slap bass, crisp drums with ghost notes, Rhodes electric piano chords.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:48:35', '2026-04-18 00:48:41');
INSERT INTO `workflow_run` VALUES (41, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"perfect\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"《perfect》的R&B心动告白\",\"coverText\":\"perfect｜翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#perfect\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Intimate, romantic, and tender; perfect for a late-night confession\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, swung beat with a steady pulse\",\"Style\":\"Contemporary R&B with smooth pop sensibilities\",\"Vocal\":\"Smooth, breathy, and intimate male vocal with gentle falsetto runs and conversational phrasing\",\"Original Style Analysis\":\"Original likely a pop ballad with romantic lyrics.\",\"Key\":\"F Major\",\"Arrangement\":\"Warm electric piano chords, deep 808 sub-bass, crisp finger snaps, atmospheric synth pads, subtle guitar licks\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-18 00:57:40', '2026-04-18 00:57:47');
INSERT INTO `workflow_run` VALUES (42, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《夜曲》的浪漫\",\"coverText\":\"夜曲｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#夜曲\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Intimate, late-night reflective vibe; perfect for solitary listening\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, syncopated 6/8 swing feel\",\"Style\":\"Contemporary R&B with smooth pop sensibilities\",\"Vocal\":\"Smooth, breathy, intimate male vocal with gentle falsetto ad-libs; relaxed, conversational phrasing\",\"Original Style Analysis\":\"Original is a melancholic pop ballad with classical piano elements.\",\"Key\":\"F minor\",\"Arrangement\":\"Warm, deep synth pads, crisp finger-snap percussion, subtle sub-bass, atmospheric synth textures\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-20 19:32:35', '2026-04-20 19:32:43');
INSERT INTO `workflow_run` VALUES (43, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《夜曲》，R&B版太上头了\",\"coverText\":\"夜曲｜翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#夜曲\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Late-night introspective and melancholic vibe, perfect for solitary listening\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, steady 6/8 swing feel\",\"Style\":\"Contemporary R&B with smooth pop sensibilities\",\"Vocal\":\"Smooth, breathy, and intimate male vocal with gentle falsetto ad-libs\",\"Original Style Analysis\":\"Original is a melancholic Chinese pop ballad.\",\"Key\":\"F minor\",\"Arrangement\":\"Warm, deep synth pads, crisp finger-snap percussion, subtle sub-bass, clean electric guitar licks\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-20 19:41:57', '2026-04-20 19:42:04');
INSERT INTO `workflow_run` VALUES (44, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《夜曲》的温柔\",\"coverText\":\"夜曲｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#夜曲\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Introspective, late-night melancholy with a soothing, sensual undercurrent.\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, steady 6/8 swing with a gentle push.\",\"Style\":\"Contemporary R&B with atmospheric pop sensibility\",\"Vocal\":\"Smooth, breathy, and intimate male vocal with relaxed phrasing and subtle melisma.\",\"Original Style Analysis\":\"Original likely a melancholic pop ballad with piano focus.\",\"Key\":\"F minor\",\"Arrangement\":\"Warm, deep synth pads, crisp finger-snap percussion, subtle sub-bass, sparse electric piano chords, and atmospheric vocal ad-libs.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-20 19:45:08', '2026-04-20 19:45:16');
INSERT INTO `workflow_run` VALUES (45, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"夜曲\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[],\"tempo\":\"\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《夜曲》，R&B版太上头了\",\"coverText\":\"如果《夜曲》变成翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#夜曲\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Late-night introspective and melancholic vibe, perfect for solitary listening\",\"Tempo\":\"70 BPM\",\"Groove\":\"Laid-back, swung 6/8 feel with a steady pulse\",\"Style\":\"Contemporary R&B with smooth soul influences\",\"Vocal\":\"Smooth, breathy, and intimate male vocal with gentle falsetto ad-libs; conversational phrasing\",\"Original Style Analysis\":\"Original is a melancholic Chinese pop ballad.\",\"Key\":\"F minor\",\"Arrangement\":\"Warm electric piano chords, deep 808 bass, crisp finger snaps, atmospheric synth pads, subtle vinyl crackle\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-20 19:45:21', '2026-04-20 19:45:28');
INSERT INTO `workflow_run` VALUES (47, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"Justin biber的温柔男声\",\"mood\":[\"lazy\"],\"tempo\":\"90\",\"language\":\"English\",\"extraRemark\":\"指弹吉他伴奏\"}', '{\"title\":\"慵懒的午后，听《想念拟人化》的温柔\",\"coverText\":\"如果《想念拟人化》变成翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, introspective, and cozy; perfect for a relaxed afternoon or late-night chill.\",\"Tempo\":\"90 BPM\",\"Groove\":\"Laid-back, steady, and slightly swung R&B groove.\",\"Style\":\"Contemporary R&B with fingerstyle guitar\",\"Vocal\":\"Soft, breathy, and intimate male vocal with gentle falsetto transitions; relaxed, conversational phrasing with subtle R&B melisma.\",\"Original Style Analysis\":\"Likely a sentimental Mandopop ballad.\",\"Key\":\"F Major\",\"Arrangement\":\"Fingerstyle acoustic guitar as the main accompaniment, warm synth pads, subtle bass line, crisp finger snaps, and sparse, clean electric guitar embellishments.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:17:32', '2026-04-21 14:17:39');
INSERT INTO `workflow_run` VALUES (48, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"Justin biber的温柔男声\",\"mood\":[\"lazy\"],\"tempo\":\"90\",\"language\":\"English\",\"extraRemark\":\"指弹吉他伴奏\"}', '{\"title\":\"《想念拟人化》慵懒的午后独白\",\"coverText\":\"如果《想念拟人化》变成翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Emotionally vulnerable and lazily introspective. Feels like a solitary, sun-drenched afternoon in a quiet room, wrapped in a haze of warm nostalgia and soft reflection.\",\"Tempo\":\"Relaxed, swaying mid-tempo ~90 BPM.\",\"Groove\":\"A laid-back, slightly swung 6/8 feel with a gentle push-and-pull, creating a hypnotic, drifting motion.\",\"Style\":\"Contemporary R&B with intimate acoustic soul textures, blending warm fingerstyle guitar with smooth vocal harmonies.\",\"Vocal\":\"Justin Bieber-inspired gentle, breathy male tenor with a soft, intimate delivery. Conversational phrasing with subtle emotional cracks, incorporating smooth falsetto lifts and effortless, understated melodic runs.\",\"Original Style Analysis\":\"Original is a sentimental Mandopop ballad.\",\"Key\":\"G Major, bright yet introspective.\",\"Arrangement\":\"Fingerpicked acoustic guitar as the core, using delicate arpeggios and occasional harmonics. Subtle, warm synth pads and a soft, muted electric piano layer provide a cushioned backdrop. Minimalist, brushed hi-hats and a deep, rounded bass line anchor the groove.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:24:55', '2026-04-21 14:25:08');
INSERT INTO `workflow_run` VALUES (49, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"lazy\"],\"tempo\":\"85\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"《想念拟人化》慵懒的午后想念蔓延\",\"coverText\":\"想念拟人化这样唱，太动听了\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"\",\"Tempo\":\"Slow, lazy R&B groove ~85 BPM.\",\"Groove\":\"A slow, unhurried, and slightly swung pulse. The bass and guitar create a gentle, rolling forward motion that feels organic and relaxed.\",\"Style\":\"Contemporary R&B with intimate acoustic textures, warm soulful undertones, and a minimalist studio jam feel.\",\"Vocal\":\"\",\"Emotional tone\":\"Lazy, wistful, and introspective. Listening scene: A hazy, quiet late afternoon in a sunlit room. Overall vibe: Intimate, soul-searching, and effortlessly smooth.\",\"Original Style Analysis\":\"Original is a sentimental Mandopop ballad.\",\"Key\":\"F major, warm and introspective.\",\"Arrangement\":\"Fingerstyle acoustic guitar as the core, using gentle arpeggios and soft harmonics. Subtle, warm electric piano chords pad the background. A soft, deep synth bass provides a foundational pulse. No drums, only occasional brushed shaker for texture.\",\"陶喆的声线\":\"warm, slightly breathy, and conversational. Emotionally nuanced phrasing with gentle falsetto flourishes and subtle, effortless melodic runs. Intimate, close-mic\'d delivery.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:25:48', '2026-04-21 14:25:59');
INSERT INTO `workflow_run` VALUES (50, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"lazy\"],\"tempo\":\"85\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"《想念拟人化》慵懒午后 想念有了形状\",\"coverText\":\"一首《想念拟人化》，唱出动听\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy, introspective, and wistful emotional tone.\\nA late afternoon scene in a sun-drenched, slightly dusty room.\\nOverall vibe is intimate, hazy, and tenderly melancholic.\",\"Tempo\":\"Slow, drifting mid-tempo ~85 BPM, with a relaxed heartbeat pulse.\",\"Groove\":\"A slow, swaying 6/8 feel with a gentle triplet shuffle, creating a hypnotic and unhurried flow.\",\"Style\":\"Contemporary R&B with lo-fi intimacy and acoustic soul textures, warm and spacious.\",\"Vocal\":\"David Tao\'s signature breathy, warm, and conversational tenor tone.\\nIntimate, slightly slurred phrasing with emotional rawness.\\nEmploy light falsetto flourishes and subtle, effortless melodic runs.\",\"Original Style Analysis\":\"Original is a sentimental Mandarin pop ballad with gentle acoustic arrangement.\",\"Key\":\"G Major, evoking a warm, nostalgic, and slightly bittersweet openness.\",\"Arrangement\":\"Fingerstyle acoustic guitar as the core, using delicate arpeggios and harmonics.\\nSubtle, deep electric bass providing a soft foundation.\\nAtmospheric synth pads and sparse, distant electric piano chords for texture.\\nNo drums; percussion implied through guitar body taps and string noise.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:30:26', '2026-04-21 14:30:39');
INSERT INTO `workflow_run` VALUES (51, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《想念拟人化》的浪漫\",\"coverText\":\"如果《想念拟人化》变成情歌\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic, late-night introspection. The vibe is intimate, yearning, and warmly nostalgic, perfect for a solitary, rain-streaked window scene.\",\"Tempo\":\"Slow, swaying R&B groove ~91 BPM.\",\"Groove\":\"A laid-back, head-nodding 6/8 swing feel with a prominent, pillowy kick and snare on the 2 and 4, accented by tight, brushed hi-hats.\",\"Style\":\"Contemporary R&B with lo-fi textural elements and subtle neo-soul chord extensions.\",\"Vocal\":\"Breathy, intimate, and conversational male vocal tone. Emotionally nuanced phrasing with gentle melismas and effortless falsetto transitions in the ad-libs. Close-mic\'d, dry recording with a touch of vintage slap-back delay.\",\"Original Style Analysis\":\"Original is a sentimental Mandarin pop ballad.\",\"Key\":\"F minor, for a deep, intimate, and melancholic warmth.\",\"Arrangement\":\"Warm, muted electric piano chords with gentle side-chain compression. Soft, finger-picked nylon-string guitar harmonics. A deep, rounded synth bass line. Subtle vinyl crackle and atmospheric pad swells in the background.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:31:35', '2026-04-21 14:31:48');
INSERT INTO `workflow_run` VALUES (52, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《想念拟人化》的浪漫\",\"coverText\":\"想念拟人化｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic, introspective, and yearning. Feels like a late-night drive through city lights or a quiet, intimate moment alone with thoughts. A smooth, soulful, and deeply personal vibe.\",\"Tempo\":\"Slow, swaying R&B groove ~91 BPM.\",\"Groove\":\"A relaxed, heartbeat-like kick and snare pattern with prominent, syncopated hi-hats, creating a slow-burning, head-nodding sway.\",\"Style\":\"Contemporary R&B with smooth, atmospheric production and subtle lo-fi textural touches.\",\"Vocal\":\"Breathy, warm, and intimate male vocal tone. Conversational, emotive phrasing with subtle vibrato. Tasteful, melodic R&B runs and light falsetto ad-libs in the background.\",\"Original Style Analysis\":\"Original is a sentimental Mandopop ballad.\",\"Key\":\"F minor, for a soulful, intimate, and slightly melancholic mood.\",\"Arrangement\":\"Warm, muted electric piano chords with gentle reverb. Soft, sub-bass line providing foundation. Layered, ethereal synth pads in the background. Clean, fingerpicked electric guitar accents with slight chorus effect.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:38:35', '2026-04-21 14:38:47');
INSERT INTO `workflow_run` VALUES (53, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"lazy\"],\"tempo\":\"85\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"《想念拟人化》慵懒午后 想念有了形状\",\"coverText\":\"想念拟人化｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"A lazy, introspective afternoon vibe. Emotional tone is wistful and tender, like reminiscing alone by a window with soft, golden-hour light. Overall intimate and unpolished, bedroom-studio feel.\",\"Tempo\":\"Slow, relaxed mid-tempo ~85 BPM.\",\"Groove\":\"A laid-back, slightly swung 6/8 feel with a gentle, pulsing heartbeat rhythm. The bass and guitar create a soft, rolling motion.\",\"Style\":\"Contemporary R&B with lo-fi intimacy and acoustic soul textures.\",\"Vocal\":\"David Tao\'s signature warm, slightly raspy tenor tone. Conversational, intimate phrasing with breathy delivery. Use of smooth, effortless falsetto transitions and subtle, emotional melodic runs.\",\"Original Style Analysis\":\"Original is a sentimental Mandarin ballad with gentle acoustic arrangement.\",\"Key\":\"F major, warm and introspective.\",\"Arrangement\":\"Fingerstyle acoustic guitar as the core, with soft, clean plucking and occasional harmonics. Subtle, warm bass guitar holding the low end. Minimalist atmospheric pads and a faint vinyl crackle texture in the background.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:39:16', '2026-04-21 14:39:27');
INSERT INTO `workflow_run` VALUES (54, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《想念拟人化》的浪漫\",\"coverText\":\"想念拟人化｜情歌\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic longing and intimate reflection. Feels like a late-night, candlelit room, solitary yet full of warm memory. A cozy, soul-baring vibe.\",\"Tempo\":\"Slow, swaying R&B groove ~91 BPM.\",\"Groove\":\"A laid-back, hip-hop influenced drum pattern with soft, brushed snare hits and a prominent, syncopated kick. Gentle, finger-picked bass providing a fluid, melodic pulse.\",\"Style\":\"Contemporary R&B with smooth neo-soul textures and a warm, intimate soundscape.\",\"Vocal\":\"Breathy, intimate, and warm male vocal tone. Conversational, emotionally nuanced phrasing with gentle vibrato. Subtle, effortless falsetto flourishes and smooth melodic runs.\",\"Original Style Analysis\":\"Original is a sentimental Mandopop ballad.\",\"Key\":\"G Minor, for a soulful and introspective mood.\",\"Arrangement\":\"Warm, muted electric guitar arpeggios. Soft, sustained synth pads and a deep, rounded bassline. Subtle, glistening electric piano chords and atmospheric vinyl crackle in the background.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:39:39', '2026-04-21 14:39:52');
INSERT INTO `workflow_run` VALUES (55, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"深夜单曲循环《想念拟人化》的浪漫\",\"coverText\":\"如果《想念拟人化》变成情歌\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic, late-night introspection; the feeling of lying awake, missing someone, wrapped in a cozy, melancholic yet tender atmosphere.\",\"Tempo\":\"Slow, swaying R&B groove ~91 BPM.\",\"Groove\":\"A laid-back, heartbeat pulse with a slight swing, driven by the bass and crisp, off-beat percussion.\",\"Style\":\"Contemporary R&B with smooth, atmospheric production and subtle lo-fi textural elements.\",\"Vocal\":\"Breathy, intimate, and warm male vocal. Conversational, yearning phrasing with gentle falsetto lifts and subtle, controlled melodic runs for emotional emphasis.\",\"Original Style Analysis\":\"Original is a sentimental Mandarin pop ballad.\",\"Key\":\"G minor, for a soulful and introspective mood.\",\"Arrangement\":\"Warm, muted electric piano chords with soft rhodes pads. Clean, melodic bassline. Subtle, brushed hi-hats and finger-snaps for percussion. Atmospheric synth pads in the background swell gently.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:40:51', '2026-04-21 14:41:01');
INSERT INTO `workflow_run` VALUES (56, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"lazy\"],\"tempo\":\"85\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"《想念拟人化》慵懒R&B，陶喆声线吉他指弹\",\"coverText\":\"想念拟人化｜翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"A lazy, introspective afternoon vibe, perfect for solitary reflection or a cozy, low-key setting.\",\"Tempo\":\"A slow, relaxed tempo of 85 BPM.\",\"Groove\":\"A steady, unhurried pulse driven by the guitar\'s rhythmic picking and a soft, side-stick snare on beats two and four.\",\"Style\":\"A smooth, contemporary R&B reinterpretation with a laid-back feel.\",\"Vocal\":\"A smooth, slightly raspy tenor tone inspired by David Tao\'s phrasing, with relaxed, conversational delivery. Features gentle falsetto flourishes and effortless, behind-the-beat rhythmic feel.\",\"Original Style Analysis\":\"The original song likely features a sentimental Mandopop ballad style with melodic vocals and piano or string accompaniment.\",\"Key\":\"A warm and soulful key, such as F major.\",\"Arrangement\":\"Centered on a clean, intricate fingerstyle acoustic guitar accompaniment. Subtle, deep electric bass provides a soft foundation. Atmospheric pads and sparse, brushed percussion textures fill the space. The production is intimate, dry, and crisp.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:49:33', '2026-04-21 14:49:45');
INSERT INTO `workflow_run` VALUES (57, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"《想念拟人化》的浪漫R&B时刻\",\"coverText\":\"如果《想念拟人化》变成情歌\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic and introspective, evoking a late-night drive or a cozy, intimate moment of longing and affection.\",\"Tempo\":\"A relaxed tempo of 91 BPM, creating a steady and intimate groove.\",\"Groove\":\"A laid-back, head-nodding groove built on a simple yet punchy kick and snare pattern with syncopated hi-hat rhythms.\",\"Style\":\"Contemporary R&B with smooth, soulful chords and a laid-back rhythmic feel.\",\"Vocal\":\"A smooth, breathy male vocal with intimate, conversational phrasing. Features gentle falsetto runs and subtle, emotive ad-libs for a soulful and personal delivery.\",\"Original Style Analysis\":\"The original song likely features a sentimental Mandopop ballad style with gentle acoustic arrangements.\",\"Key\":\"Warm and soulful key of F major, supporting emotive vocal melodies.\",\"Arrangement\":\"Centered on a clean electric piano riff and a deep, rounded synth bass line. Crisp finger-snaps and tight, brushed hi-hats provide the rhythmic backbone. Atmospheric pad swells and subtle guitar licks add texture in the background for a polished, modern production.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:50:08', '2026-04-21 14:50:20');
INSERT INTO `workflow_run` VALUES (58, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"《想念拟人化》的浪漫R&B，让思念有声音\",\"coverText\":\"想念拟人化｜R&B翻唱\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic and wistful, evoking a late-night scene of nostalgic reflection and tender longing.\",\"Tempo\":\"A relaxed, steady tempo of 91 BPM, creating a laid-back and intimate feel.\",\"Groove\":\"A laid-back, head-nodding groove driven by a solid bass and tight, understated drum programming with occasional swung hi-hats.\",\"Style\":\"Contemporary R&B with smooth, soulful grooves and warm, atmospheric production.\",\"Vocal\":\"A smooth, breathy, and emotive male or female vocal with gentle falsetto flourishes. Phrasing is relaxed and conversational, with subtle melismatic runs and intimate, close-mic delivery.\",\"Original Style Analysis\":\"The original song likely features a sentimental Mandopop ballad style with gentle acoustic instrumentation and emotive vocal delivery.\",\"Key\":\"A smooth and soulful key, such as F major or D minor, to support the romantic mood.\",\"Arrangement\":\"Centered on a warm, deep electric bass line and crisp, finger-snapped backbeat. Layers include shimmering electric piano chords, sparse clean guitar licks, and subtle synth pads for atmosphere. The production is clean, intimate, and slightly wet with reverb.\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:54:47', '2026-04-21 14:55:00');
INSERT INTO `workflow_run` VALUES (59, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"\",\"mood\":[\"romantic\"],\"tempo\":\"91\",\"language\":\"English\",\"extraRemark\":\"\"}', '{\"title\":\"《想念拟人化》的R&B浪漫演绎\",\"coverText\":\"想念拟人化｜情歌\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\",\"#情歌\"],\"suggestion\":\"建议使用情侣、回忆类画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Romantic longing, late-night city window scene\",\"Tempo\":\"91 BPM, laid-back groove\",\"Groove\":\"Mid-tempo swing, relaxed pocket\",\"Style\":\"Contemporary R&B, smooth atmospheric\",\"Vocal\":\"Soulful male tenor, smooth falsetto transitions, gentle vibrato, conversational phrasing, close-mic intimacy\",\"Original Style Analysis\":\"Mandopop ballad\",\"Key\":\"F minor, intimate mood\",\"Arrangement\":\"Warm synth pads, clean electric guitar chords, subtle bassline, crisp drum programming with soft snare, sparse piano accents, modern polished mix\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:57:46', '2026-04-21 14:57:53');
INSERT INTO `workflow_run` VALUES (60, 1, 'ai_cover_prompt', 'SUCCESS', '{\"songName\":\"想念拟人化\",\"style\":\"R&B\",\"artist\":\"陶喆的声线\",\"mood\":[\"lazy\"],\"tempo\":\"85\",\"language\":\"English\",\"extraRemark\":\"吉他指弹伴奏\"}', '{\"title\":\"《想念拟人化》慵懒蓝调节奏\",\"coverText\":\"如果《想念拟人化》变成翻唱版\",\"tags\":[\"#AI翻唱\",\"#AI音乐\",\"#想念拟人化\",\"#R&B翻唱\"],\"suggestion\":\"建议搭配氛围感十足的视频画面，剪辑节奏适中即可，适合都市夜景、车窗、街头氛围。\",\"prompt\":{\"Mood\":\"Lazy afternoon, wistful longing\",\"Tempo\":\"85 BPM, slow groove\",\"Groove\":\"Slow, relaxed backbeat\",\"Style\":\"R&B, smooth, laid-back\",\"Vocal\":\"David Tao\'s vocal tone, smooth falsetto, relaxed phrasing, breathy\",\"Original Style Analysis\":\"Mandopop ballad\",\"Key\":\"F minor, melancholic, warm\",\"Arrangement\":\"Fingerstyle acoustic guitar main, soft electric piano pads, subtle bass, clean mix\"}}', '{\"model\":\"deepseek-chat\",\"source\":\"DeepSeek-Chat\"}', NULL, '2026-04-21 14:58:53', '2026-04-21 14:59:00');

-- ----------------------------
-- Table structure for workflow_step_run
-- ----------------------------
DROP TABLE IF EXISTS `workflow_step_run`;
CREATE TABLE `workflow_step_run`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `run_id` bigint NOT NULL COMMENT '所属运行记录ID',
  `step_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '步骤编码',
  `step_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '步骤名称',
  `step_order` int NOT NULL COMMENT '步骤顺序',
  `step_status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '步骤状态：PENDING/RUNNING/SUCCESS/FAILED',
  `input_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '步骤输入快照JSON',
  `output_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '步骤输出快照JSON',
  `error_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '步骤错误信息',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_step_run_run_id`(`run_id` ASC) USING BTREE,
  INDEX `idx_step_run_order`(`step_order` ASC) USING BTREE,
  INDEX `idx_step_run_status`(`step_status` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '流程步骤记录表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of workflow_step_run
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
